---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pr-pipeline
spec:
  params:
    - name: target-repository
      description: the git repo containing source code
    - name: target-branch
      description: branch
    - name: target-commit-id
      description: commit id in the target 
    - name: pr-branch
      description: branch
    - name: pr-commit-id
      description: the git revision/commit for the git repo
      default: ""
    - name: pr-repository
      description: pr repo
    - name: pr-commit-timestamp
    - name: pr-url
      description: pr URL
    - name: scm-type
    - name: project-id
      default: ""
    - name: pipeline-debug
      description: toggles debug mode for the pipeline
    - name: serving-ns
      description: modelmesh serving namespace
    - name: kubernetes-cluster
      description: cluster name
    - name: docker-password
      description: iam api key
    - name: ibmapikey
      description: the ibmcloud api key
    - name: resource-group
      description: resource group
      default: default
    - name: org
      description: organization
    - name: region
      description: region
    - name: space
      description: space      
  workspaces:
    - name: pipeline-ws

  tasks:
    - name: git-clone
      taskRef:
        name: git-clone-repo
      params:
        - name: continuous-delivery-context-secret
          value: "secure-properties"
        - name: ibmcloud-apikey-secret-key
          value: "apikey"
        - name: repository
          value: $(params.target-repository)
        - name: branch
          value: $(params.target-branch)
        - name: revision
          value: $(params.target-commit-id)
        - name: pr-repository
          value: $(params.pr-repository)
        - name: pr-branch
          value: $(params.pr-branch)
        - name: pr-revision
          value: $(params.pr-commit-id)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
      workspaces:
        - name: output
          workspace: pipeline-ws
    - name: fvt-tests-status-pending
      taskRef:
        name: git-set-commit-status
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
      params:
        - name: repository
          value: $(params.target-repository)
        - name: revision
          value: $(params.pr-commit-id)
        - name: context
          value: "FVT tests"
        - name: description
          value: "FVT tests successfull"
        - name: state
          value: "pending"
        - name: pipeline-debug
          value: $(params.pipeline-debug)
    - name: setup-env
      runAfter: [git-clone]
      taskRef:
        name: test
      params:
        - name: repository
          value: $(params.target-repository)
        - name: revision
          value: $(params.pr-commit-id)
        - name: apikey
          value: $(params.ibmapikey)
        - name: registry-namespace
          value: chhuang
        - name: docker-username
          value: iamapikey
        - name: docker-password
          value: $(params.docker-password)
        - name: resource-group
          value: $(params.resource-group)
        - name: org
          value: $(params.org)
        - name: region
          value: $(params.region)
        - name: space
          value: $(params.space)
        - name: skip-clone
          value: "1"
        - name: kubernetes-cluster
          value: $(params.kubernetes-cluster)
        - name: serving-ns
          value: $(params.serving-ns)
      workspaces:
      - name: task-pvc
        workspace: pipeline-ws
    - name: fvt-tests
      runAfter: [setup-env]
      taskRef:
        name: build-images-dnd
      params:
        - name: apikey
          value: $(params.ibmapikey)
        - name: image-name
          value: modelmesh-serving
        - name: docker-root
          value: .
        - name: docker-file
          value: ""
        - name: registry-url
          value: ""
        - name: registry-namespace
          value: ""
        - name: docker-username
          value: iamapikey
        - name: docker-password
          value: $(params.docker-password)
        - name: dockerhub-username
          value: ""
        - name: dockerhub-password
          value: ""
        - name: dockerhub-namespace
          value: ""
        - name: publish-tag
          value: ""
        - name: run-task
          value: build_test
      workspaces:
        - name: task-pvc
          workspace: pipeline-ws
  finally:
    - name: cleanup-namespace
      taskRef:
        name: iks-test
      params:
        - name: apikey
          value: $(params.ibmapikey)
        - name: kubernetes-cluster
          value: $(params.kubernetes-cluster)
        - name: serving-ns
          value: $(params.serving-ns)
        - name: resource-group
          value: $(params.resource-group)
        - name: org
          value: $(params.org)
        - name: region
          value: $(params.region)
        - name: space
          value: $(params.space)
        - name: test-commands
          value: |
            kubectl delete ns $(params.serving-ns) || true
            kubectl delete job --all -n default || true
      workspaces:
      - name: task-pvc
        workspace: pipeline-ws
    - name: fvt-tests-status-finished
      taskRef:
        name: git-set-commit-status
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
      params:
        - name: repository
          value: $(params.target-repository)
        - name: revision
          value: $(params.pr-commit-id)
        - name: context
          value: "FVT tests"
        - name: description
          value: "FVT tests successfull"
        - name: state
          value: "$(tasks.fvt-tests.status)"
        - name: pipeline-debug
          value: $(params.pipeline-debug)